# Generated by Django 4.0.3 on 2022-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentUsername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
