# Generated by Django 4.0.3 on 2022-03-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_post_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_modify_time',
        ),
    ]
