# Generated by Django 4.0.3 on 2022-03-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_restaurantfollow_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_shares',
        ),
    ]
