# Generated by Django 4.0.3 on 2022-03-22 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid format for phone number. Example: 123-123-1234', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
