# Generated by Django 4.0.3 on 2022-03-22 19:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('primary_image', models.ImageField(blank=True, upload_to='restaurants/primary_image/')),
                ('banner', models.ImageField(blank=True, upload_to='restaurants/banner/')),
                ('image', models.ImageField(blank=True, upload_to='restaurants/image/')),
                ('theme', models.CharField(blank=True, choices=[('italian', 'Italian'), ('asian', 'Asian'), ('bistro', 'Bistro'), ('newamerican', 'New American'), ('fastfood', 'Fast Food'), ('foodtruck', 'Food Truck'), ('buffet', 'Buffet')], max_length=128)),
                ('website', models.URLField(blank=True, max_length=253)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid format for phone number. Example: 123-123-1234', regex='^\\d{3}-\\d{3}-\\d{4}$')])),
                ('fax', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid format for phone number. Example: 123-123-1234', regex='^\\d{3}-\\d{3}-\\d{4}$')])),
                ('number_likes', models.IntegerField(blank=True, default=0)),
                ('number_follows', models.IntegerField(blank=True, default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=128)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/image/')),
                ('position', models.IntegerField(blank=True, default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('details', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
