# Generated by Django 4.0.3 on 2022-04-26 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_theme_restaurant_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Invalid format for postal code. Example: A1A4C4. Ensure to use capital letters only', regex='^[ABCEGHJ-NPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z]\\d[ABCEGHJ-NPRSTV-Z]\\d$')]),
        ),
    ]
